### ISSUE TITLE
403 error when sending a message

### ISSUE THREAD

**Issue by BlueskyFR** [huggingface/chat-ui#1057]
Hi! When deploying locally, and sending the first message in a conversation, I get this error message:
![aa](https://github.com/huggingface/chat-ui/assets/25421460/8926219d-dfb6-4fce-8ec6-d39826b0d883)

Please note that I am accessing the app through `http://local_ip:3000`.
There may be some auth problems, though I did not find any helpful information on that matter.

My `docker-compose.yml` is as follows:
```yml
services:
  hf-chat:
    image: ghcr.io/huggingface/chat-ui-db
    volumes:
      - ./hf-chat-data/.env.local:/app/.env.local
    ports:
      - 3000:3000
    restart: unless-stopped
```

Thanks in advance!
