### ISSUE TITLE
Error when deploying chat-ui on k8s

### ISSUE THREAD

**Issue by xyxxxxx** [huggingface/chat-ui#1143]
I tried to use the chart in the repo to deploy chat-ui in kubernetes, but encountered the following error:

```
NotFound [Error]: Not found: /healthcheck
    at resolve2 (file:///app/.svelte-kit/output/server/index.js:2812:18)
    at resolve (file:///app/.svelte-kit/output/server/index.js:2639:34)
    at Object.handle (file:///app/.svelte-kit/output/server/chunks/hooks.server.js:333:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///app/.svelte-kit/output/server/index.js:2637:22)
    at async file:///app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:185:5 {
  status: 404
}
```

As a reference, the modified values.yaml is as follows:

```yaml
image:
  repository: ghcr.io/huggingface
  name: chat-ui
  tag: 0.8.3
  pullPolicy: IfNotPresent

replicas: 1

domain: huggingface.co

service:
  type: NodePort
  annotations: { }

ingress:
  path: "/"
  annotations: { }

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
nodeSelector: {}
tolerations: []

envVars:
  MONGODB_URL: mongodb://mongo-mongodb.ns.svc.cluster.local
externalSecrets:
  enabled: false
  secretStoreName: ""
  secretName: ""
  parameters: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: ""
  targetCPUUtilizationPercentage: ""

monitoring:
  enabled: false
```

the complete log:

[app.log](https://github.com/huggingface/chat-ui/files/15321118/app.log)
