### ISSUE TITLE
MODELS=`[ variable problem when I docker run

### ISSUE THREAD

**Issue by avirgos** [huggingface/chat-ui#1436]
Hello,

I want to use Ollama to use Mistral model and I followed the documentation below : https://huggingface.co/docs/chat-ui/configuration/models/providers/ollama 

`deploy.sh` :

```sh
#!/bin/bash

sudo docker compose down
sudo docker rm -f mongodb && sudo docker rm -f chat-ui

# nginx and ollama
sudo docker compose up -d

# mongodb
sudo docker run -d -p 27017:27017 -v mongodb-data:/data/db --name mongodb --network backend mongo:latest

# chat-ui
sudo docker run -d -p 3000:3000 --env-file .env.local -v chat-ui:/data --name chat-ui --network proxy ghcr.io/huggingface/chat-ui-db && sudo docker network connect backend chat-ui
```
`docker-compose.yml` :

```YAML
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    restart: unless-stopped

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama-with-ca
    container_name: ollama
    ports:
      - 11434:11434
    networks:
      - backend
    environment:
      - HTTPS_PROXY=http://<username>:<password>@proxy.test.fr:8090
    volumes:
      - ollama-data:/data
    restart: unless-stopped
    entrypoint: ["/bin/bash", "start-mistral.sh"]

networks:
  backend:
  proxy:
    external: true

volumes:
  ollama-data:
```

`.env.local` :

```
MONGODB_URL=mongodb://mongodb:27017
HF_TOKEN=hf_*****

MODELS=`[
  {
    "name": "Ollama Mistral",
    "chatPromptTemplate": "<s>{{#each messages}}{{#ifUser}}[INST] {{#if @first}}{{#if @root.preprompt}}{{@root.preprompt}}\n{

{/if}

}{

{/if}

} {{content}} [/INST]{{/ifUser}}{{#ifAssistant}}{{content}}</s> {{/ifAssistant}}{{/each}}",
    "parameters": {
      "temperature": 0.1,
      "top_p": 0.95,
      "repetition_penalty": 1.2,
      "top_k": 50,
      "truncate": 3072,
      "max_new_tokens": 1024,
      "stop": ["</s>"]
    },
    "endpoints": [
      {
        "type": "ollama",
        "url" : "ollama://ollama:11434",
        "ollamaName" : "mistral"
      }
    ]
  }
]`
```

When I start my script, at the end of the execution, the container doesn't want to launch, I get the following error :

```sh
docker: poorly formatted environment: variable '"name": "Ollama Mistral",' contains whitespaces.
See 'docker run --help'.
```

I already tried to put `chat-ui` and `mongodb` containers in the `docker-compose.yml` and  it doesn't works, same as this issue : https://github.com/huggingface/chat-ui/issues/614 

Any solutions ?

Thanks in advance.
