### ISSUE TITLE
Mistral api configuration

### ISSUE THREAD

**Issue by JonasMedu** [huggingface/chat-ui#1472]
I'd like to setup a local deployment using **only the mistral API**: https://docs.mistral.ai/api.

Can i use ChatUI without an HF deployment and Cloudflare account?

I leave the .env unchanged and overwrite the env.local with the following code

```yml
AGENT_ID=<my_agent_id_from_mistral>
MISTRAL_API_KEY==<mytoken>
MODELS='[
    {
      "name": "mistral-large",
      "displayName": "mistralai",
      "description": "Mistral standard",
      "websiteUrl": "https://docs.mistral.ai/",
      "preprompt": "",
      "parameters": {
        "temperature": 0.1,
        "top_p": 0.95,
        "top_k": 5,
        "stream": true,
        "agent_id": "{AGENT_ID}",
        "tool_choice": "auto",
        "max_new_tokens": 4096
      },
      "endpoints": [
          {
              "type": "openai",
              "baseURL": "https://api.mistral.ai/v1",
              "defaultHeaders": {
                  "Authorization": "Bearer {MISTRAL_API_KEY}"
              }
          }
      ]
    },
    {
    "name": "mistral-embed",
    "displayName": "Mistral-embedbedings",
    "description": "Mistral embedding model.",
    "chunkCharLength": 1024,
    "endpoints": [
        {
            "type": "openai",
            "baseURL": "https://api.mistral.ai/v1",
            "defaultHeaders": {
                "Authorization": "Bearer {MISTRAL_API_KEY}"
            }
        }
    ]
  }
]'
MONGODB_URL=mongodb://localhost:27017/
PUBLIC_APP_ASSETS=chatui
PUBLIC_APP_COLOR=blue
PUBLIC_APP_NAME="Mistral Local"
```
Not quite sure though if the agend_id is overwritten by the "name".
