### ISSUE TITLE
No background color set

### ISSUE THREAD

**Issue by Oneechan69** [huggingface/chat-ui#1622]
The solution is simple (and can be done by users with an addon like Stylus):

```css
body {
background-color: #FFF;
}
```
<img width="1197" alt="CleanShot 2024-12-10 at 03 15 22@2x copy 2" src="https://github.com/user-attachments/assets/b355fe08-698a-4e6b-a897-16ba89639c47">
