### ISSUE TITLE
`searXNG` search shows "Failed to fetch or parse JSON"

### ISSUE THREAD

**Issue by ljw20180420** [huggingface/chat-ui#1628]
## Bug description

I use `searXNG` as the backend of web search. I test `searXNG` by directly visit its port in the browser. When I use it in `chat-ui`, `searXNG` returns some contents. But `web search` failed to fetch or parse JSON.
```
Searching SearXNG
some content
An error occurred
Failed to fetch or parse JSON
```

My `.env.local` is
```
MODELS=`[
  {
    "name": "microsoft/Phi-3-mini-4k-instruct-gguf",
    "tokenizer": "microsoft/Phi-3-mini-4k-instruct-gguf",
    "preprompt": "",
    "chatPromptTemplate": "<s>{{preprompt}}{{#each messages}}{{#ifUser}}<|user|>\n{{content}}<|end|>\n<|assistant|>\n{{/ifUser}}{{#ifAssistant}}{{content}}<|end|>\n{{/ifAssistant}}{{/each}}",
    "parameters": {
      "stop": ["<|end|>", "<|endoftext|>", "<|assistant|>"],
      "temperature": 0.7,
      "max_new_tokens": 1024,
      "truncate": 3071
    },
    "endpoints": [{
      "type" : "llamacpp",
      "url": "http://chat-ui-llama.cpp:8080"
    }],
  },
]`

SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&format=json

PUBLIC_ORIGIN="http://localhost"
```
I use docker. The `compose.yaml` is
```yaml
services:
  chat-ui-db:
    depends_on:
      # - TGI
      # - TEI
      - searxng
      - llama.cpp
    restart: always
    container_name: chat-ui-db
    image: ghcr.io/huggingface/chat-ui-db:latest
    volumes:
      - "./docker-images/chat-ui/.env.local:/app/.env.local"
      - "./docker-images/chat-ui/chat:/data"
    ports:
      - "3000:3000"

  searxng:
    restart: always
    container_name: chat-ui-searxng
    image: searxng/searxng:latest
    volumes:
      - "./docker-images/chat-ui/searxng:/etc/searxng"
    ports:
      - "55609:8080"

  llama.cpp:
    restart: always
    container_name: chat-ui-llama.cpp
    image: ghcr.io/ggerganov/llama.cpp:server
    volumes:
      - "./docker-images/chat-ui/llama.cpp:/models"
    command: -m /models/Phi-3-mini-4k-instruct-gguf/Phi-3-mini-4k-instruct-q4.gguf -c 4096
```

### Logs

```
// logs here if relevant
```

### Specs

- **OS**:
- **Browser**:
- **chat-ui commit**:

**Comment by ljw20180420** [comment]
I know the reason. `chat-ui` parse the respone of `searXNG` as `JSON`.
```
SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&format=json
```
Note the `&format=json`. According to https://docs.searxng.org/dev/search_api.html:

format: optional
    [ json, csv, rss ]
    Output format of results. Format needs to be activated in [search:](https://docs.searxng.org/admin/settings/settings_search.html#settings-search).

So in `settings.yml` of `searXNG`,
```yml
search:
  ...
  formats:
    - html
    - json
```
Note the `- json` added to `formats:`. Otherwise, search with `&format=json` will return 403.

I think the documentation of `searXNG` https://huggingface.co/docs/chat-ui/configuration/web-search#searxng can add this.
