### ISSUE TITLE
Chat-UI throws an 403 forbidden when access settings

### ISSUE THREAD

**Issue by IT-Guy007** [huggingface/chat-ui#545]
When viewing the settings page after first setup the settings page fives the error: ```Failed to load resource: the server responded with a status of 403 (Forbidden) settings:1``` in the console. Without any explanation of what and why.

Setup:
```yaml
services:
  # Chat ui webserver
  chat-ui:
    container_name: chat
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    networks:
      default:
        ipv4_address: 172.25.0.2

  # Mongo database      
  database:
    container_name: mongo-chatui
    image: "mongo:latest"
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=chat-ui
    networks:
      default:
        ipv4_address: 172.25.0.3

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/28
          gateway: 172.25.0.1
```

And my .env.local: 
```
MONGODB_URL=mongodb://172.25.0.3:27017
PUBLIC_ORIGIN=http://localhost:3030
HF_ACCESS_TOKEN=recacted
MODELS=recated
```

What are the steps to take here? 

The database connections gets accepted according to the mongoDB instance
