### ISSUE TITLE
Docker build - multiple errors - documentation

### ISSUE THREAD

**Issue by shuther** [huggingface/chat-ui#614]
I can't find documentation to build it myself; so I tried:
`docker-compose build up`
But I got multiple errors amoung:

> chat-ui/.env: line 23: unexpected character "\"" in variable name "\"PROVIDER_URL\": \"\","

Even `source .env` returned multiple errors; I tried to change the `into a ' with no luck.

My goal was to build it and include it into a docker compose.

**Comment by TomTom101** [comment]
`"OPENID_CONFIG" is not exported `. Add this and potentially all others to `.env.local`. The simplest docker-compose.yml that works for me is this (after removing `.env`):
```yaml
version: '3.3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always

  huggingchat:
    build: 
      context: .
    ports:
      - '3000:3000'
```
